_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.11.6
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 51
                - 53
                - 55
                - 71
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 55
                - 71
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.6
            "5": 0.19.6
            "6": 4.48.3
            "8":
                - 5
            "12": 0.19.6
            "13": linux-x86_64
checkpoint_steps:
    value: 1000
gradient_accumulation_steps:
    value: 4
learning_rate:
    value: 0.0001
local:
    value: true
low_cpu_mem_usage:
    value: false
lr_scheduler_type:
    value: linear
max_length:
    value: 512
max_train_steps:
    value: null
model_name:
    value: meta-llama/Llama-3.2-1B-Instruct
num_train_epochs:
    value: 3
num_warmup_steps:
    value: 0
output_dir:
    value: output
per_device_eval_batch_size:
    value: 4
per_device_train_batch_size:
    value: 1
trust_remote_code:
    value: false
use_slow_tokenizer:
    value: false
weight_decay:
    value: 0.01
